CREATE DATABASE CARDAPIO;
USE CARDAPIO;

CREATE TABLE CATEGORIA (
	ID_CATEGORIA INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(20) NOT NULL,
    URL_IMAGEM VARCHAR(255),
    PRIMARY KEY(ID_CATEGORIA)
);

CREATE TABLE CLIENTES(
	ID_CLIENTE INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    SOBRENOME VARCHAR(100),
    CPF VARCHAR(11),
    NR_CELULAR VARCHAR(15),
    EMAIL VARCHAR(150),
    PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE PRODUTOS(
	ID_PRODUTO INT NOT NULL AUTO_INCREMENT,
    ID_CATEGORIA INT NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(255),
    IMAGEM VARCHAR(255),
    VALOR DECIMAL(5,2),
    PRIMARY KEY (ID_PRODUTO),
    CONSTRAINT FK_PRODUTO_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA (ID_CATEGORIA)
);

CREATE TABLE PEDIDOS (
	ID_PEDIDO INT NOT NULL AUTO_INCREMENT,
    ID_PRODUTO INT NOT NULL,
    ID_CLIENTE INT NOT NULL,
    QUANTIDADE INT,
    PRECO_TOTAL DECIMAL (5,2),
    PRIMARY KEY(ID_PEDIDO),
    CONSTRAINT FK_PEDIDO_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS (ID_PRODUTO),
    CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE)
);

CREATE TABLE VENDAS (
	ID_VENDA INT NOT NULL AUTO_INCREMENT,
    ID_PEDIDO INT NOT NULL,
    DATA_ATUAL DATE,
    HORA_ATUAL TIME,
    TOTAL DECIMAL(7,2),
    PRIMARY KEY (ID_VENDA),
    CONSTRAINT FK_VENDA_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS (ID_PEDIDO)
);