CREATE DATABASE DHTUBE;
USE DHTUBE;

CREATE TABLE PAIS (
	ID_PAIS INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR (100),
    PRIMARY KEY (ID_PAIS)
);

CREATE TABLE AVATAR (
	ID_AVATAR INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR (45),
    URL_IMAGEM VARCHAR (100),
    PRIMARY KEY (ID_AVATAR)
);

CREATE TABLE USUARIO (
	ID_USUARIO INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR (45),
    EMAIL VARCHAR (45),
    SENHA VARCHAR (45),
    DATA_NASCIMENTO DATE,
    CEP VARCHAR (45),
    ID_PAIS INT NOT NULL,
    ID_AVATAR INT NOT NULL,
    PRIMARY KEY (ID_USUARIO),
    CONSTRAINT FK_PAIS_USUARIO FOREIGN KEY (ID_PAIS) REFERENCES PAIS (ID_PAIS),
    CONSTRAINT FK_AVATAR_USUARIO FOREIGN KEY (ID_AVATAR) REFERENCES AVATAR (ID_AVATAR)
);

CREATE TABLE PLAYLIST (
	ID_PLAYLIST INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR (45),
    DATA_CRIACAO DATETIME,
    PRIVADO SMALLINT (6),
    ID_USUARIO INT NOT NULL,
    PRIMARY KEY (ID_PLAYLIST),
    CONSTRAINT FK_PLAYLIST_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);

CREATE TABLE VIDEO (
	ID_VIDEO INT NOT NULL AUTO_INCREMENT,
	ID_USUARIO INT NOT NULL,
    TITULO VARCHAR (100),
    DESCRICAO TEXT,
    TAMANHO DOUBLE,
    NOME_ARQUIVO VARCHAR (100),
    DURACAO DOUBLE,
    URL_IMAGEM VARCHAR (150),
    QTDE_REPRODUCOES INT,
    QTDE_LIKES INT,
    QTDE_DISLIKE INT,
    PRIVADO SMALLINT (6),
    DATA_PUBLICACAO DATETIME,
    PRIMARY KEY (ID_VIDEO),
    CONSTRAINT FK_VIDEO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);

CREATE TABLE PLAYLIST_VIDEO (
	ID_VIDEO INT NOT NULL,
    ID_PLAYLIST INT NOT NULL,
    CONSTRAINT FK_VIDEO_PLAYLIST FOREIGN KEY (ID_VIDEO) REFERENCES VIDEO (ID_VIDEO),
    CONSTRAINT FK_PLAYLIST_PLAYLIST FOREIGN KEY (ID_PLAYLIST) REFERENCES PLAYLIST (ID_PLAYLIST)
);

CREATE TABLE CANAL (
	ID_CANAL INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR (100),
    DESCRICAO TEXT,
    DATA_CRIACAO DATETIME,
    ID_USUARIO INT NOT NULL,
     PRIMARY KEY (ID_CANAL),
    CONSTRAINT FK_USUARIO_CANAL FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);